title: Zahoor Ahmed
logo: zahoor81.github.io/Zahoor Profile.jpeg
description: As a proactive and detail-oriented computer science graduate, I have cultivated a robust foundation in AI, machine learning,
and data analysis through comprehensive coursework at my university and diverse online learning platforms. 
show_downloads: false
theme: jekyll-theme-minimal
