title: Zahoor Ahmed
logo: images/Zahoor Logo.png
description: If you're too comfortable, it's time to move on. Terrified of what's next? You're on the right track."—Susan Fales-Hill
show_downloads: false
theme: jekyll-theme-minimal
