title: Zahoor Ahmed
logo: zahoor81.github.io/Zahoor Profile.jpeg
description: As a proactive and detail-oriented computer science graduate, I have cultivated a robust foundation in AI, machine learning,
and data analysis through comprehensive coursework at my university and diverse online learning platforms. My academic
journey has been complemented by the successful execution of several impactful projects within these domains, showcasing
my fervor for leveraging technology to analyze and intricate complex datasets. With a track record of achievement, I am highly
confident in my capacity to make a meaningful contribution to a dynamic organization in this ever-evolving field.
show_downloads: true
theme: jekyll-theme-minimal
